WITH TOTALUSERS AS(
    SELECT
        COUNT(USER_ID) AS COUNT
    FROM
        USERS
)
SELECT
    CONTEST_ID,
    ROUND(COUNT(USER_ID)/MAX(COUNT) * 100, 2) AS PERCENTAGE
FROM
    REGISTER
    JOIN TOTALUSERS
    ON (1=1)
GROUP BY
    CONTEST_ID
ORDER BY
    PERCENTAGE DESC,
    CONTEST_ID ASC;