WITH COUNT AS(
    SELECT
        COUNT (PRODUCT_KEY) AS PRODUCTS
    FROM
        PRODUCT
), HELPER AS(
    SELECT
        CUSTOMER_ID,
        COUNT(DISTINCT PRODUCT_KEY) AS PAY,
        MAX(PRODUCTS)               AS PODCT
    FROM
        CUSTOMER CROSS
        JOIN COUNT
    GROUP BY
        CUSTOMER_ID
)
SELECT
    CUSTOMER_ID
FROM
    HELPER
WHERE
    PODCT = PAY;