SELECT
    M.EMPLOYEE_ID,
    M.NAME,
    COUNT(E.EMPLOYEE_ID) AS REPORTS_COUNT,
    ROUND(AVG(E.AGE), 0) AS AVERAGE_AGE
FROM
    EMPLOYEES E
    JOIN EMPLOYEES M
    ON (M.EMPLOYEE_ID = E.REPORTS_TO)
GROUP BY
    M.EMPLOYEE_ID,
    M.NAME
ORDER BY
    1;