WITH COUNT AS(
    SELECT
        COUNT(DISTINCT PLAYER_ID) AS PLAYERS
    FROM
        ACTIVITY
), HELPER AS(
    SELECT
        PLAYER_ID,
        EVENT_DATE,
        ROW_NUMBER() OVER(PARTITION BY PLAYER_ID ORDER BY PLAYER_ID,
        EVENT_DATE) AS PLAYDAYS,
        LAG(EVENT_DATE,
        1,
        EVENT_DATE) OVER(PARTITION BY PLAYER_ID ORDER BY PLAYER_ID,
        EVENT_DATE) AS DAY_BEFORE,
        PLAYERS
    FROM
        ACTIVITY
        CROSS JOIN COUNT
), CALC1 AS(
    SELECT
        *
    FROM
        HELPER
    WHERE
        PLAYDAYS IN (1, 2);

), CALC2 AS(

SELECT
    PLAYERS,
    CASE
        WHEN EVENT_DATE - DAY_BEFORE != 1 THEN
            NULL
        ELSE
            1
    END     AS CONSEC
FROM
    CALC1 )
    SELECT
        ROUND(COUNT(CONSEC)/MAX(PLAYERS), 2) AS FRACTION
    FROM
        CALC2;