WITH HELPER AS(
    SELECT
        P.PRODUCT_ID,
        P.START_DATE,
        U.PURCHASE_DATE,
        P.END_DATE,
        P.PRICE,
        U.UNITS,
        P.PRICE * U.UNITS AS ACTUAL_SALE
    FROM
        PRICES    P
        LEFT JOIN UNITSSOLD U
        ON ( (PURCHASE_DATE BETWEEN START_DATE
        AND END_DATE)
        AND P.PRODUCT_ID = U.PRODUCT_ID)
)
SELECT
    PRODUCT_ID,
    CASE
        WHEN ROUND(SUM(ACTUAL_SALE)/SUM(UNITS), 2) IS NULL THEN
            0
        ELSE
            ROUND(SUM(ACTUAL_SALE)/SUM(UNITS), 2)
    END        AS AVERAGE_PRICE
FROM
    HELPER
GROUP BY
    PRODUCT_ID;