WITH CORRECT AS(
    SELECT
        VISITED_ON,
        SUM(AMOUNT) AS AMT
    FROM
        CUSTOMER
    GROUP BY
        VISITED_ON
    ORDER BY
        VISITED_ON
), WINDOW AS(
    SELECT
        VISITED_ON,
        CASE
            WHEN COUNT(VISITED_ON) OVER ( ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING
            AND CURRENT ROW ) < 7 THEN
                NULL
            ELSE
                SUM(AMT) OVER ( ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING
                AND CURRENT ROW )
        END        AS MOVING_SUM,
        CASE
            WHEN COUNT(VISITED_ON) OVER ( ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING
            AND CURRENT ROW ) < 7 THEN
                NULL
            ELSE
                AVG(AMT) OVER ( ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING
                AND CURRENT ROW )
        END        AS MOVING_AVERAGE
    FROM
        CORRECT
)
SELECT
    TO_CHAR(VISITED_ON)      AS VISITED_ON,
    MOVING_SUM               AS AMOUNT,
    ROUND(MOVING_AVERAGE, 2) AS AVERAGE_AMOUNT
FROM
    WINDOW
WHERE
    MOVING_SUM IS NOT NULL
    AND MOVING_AVERAGE IS NOT NULL
ORDER BY
    VISITED_ON;