WITH TOTALORDERS AS(
    SELECT
        COUNT(DISTINCT CUSTOMER_ID) AS NUM
    FROM
        DELIVERY
), ORDERER AS(
    SELECT
        DELIVERY_ID,
        CUSTOMER_ID,
        ORDER_DATE,
        CUSTOMER_PREF_DELIVERY_DATE,
        ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS ORD,
        NUM
    FROM
        DELIVERY
        CROSS JOIN TOTALORDERS
), FILTERER AS(
    SELECT
        NUM,
        CASE
            WHEN CUSTOMER_PREF_DELIVERY_DATE = ORDER_DATE THEN
                1
            ELSE
                NULL
        END AS COMPARE
    FROM
        ORDERER
    WHERE
        ORD = 1;

)

SELECT
    ROUND (COUNT(COMPARE)/MAX(NUM) * 100, 2) AS IMMEDIATE_PERCENTAGE
FROM
    FILTERER;